#Postgres connection
server:
  port: 9091
spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
   platform: postgres
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/postgres
   username: postgres
   password: root
  jpa:
   show-sql: true
   generate-ddl: true
   hibernate.ddl-auto: update
   properties:
    hibernate:
     jdbc:
      lob:
       non_contextual_creation: true
    initialization-mode: always

eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
    defaultZone : http://localhost:8761/eureka/
 instance:
   hostname: localhost
